### ISSUE TITLE
HACS Integration

### ISSUE THREAD

**Issue by kamahat** [benleb/ad-automoli#123]
😩 **Describe the issue/bug**
Cannot add repository to HACS via HACS=>Integration=>Custom Repositories
Got an error message : ```log Repository structure for v0.11.4 is not compliant```

😒 **Expected behavior**
Seamless Module installation via HACS 

🧠 **System**
 - AppDaemon: **0.16.5**
   -  running mode: **hassio-plugin**
 - Home-Assistant: **Home Assistant Core 2024.5.1**
   -  running mode: **hassio**
 - Python: **3.11.8**

🗒️ **Logs** 

```log
<Integration benleb/ad-automoli> Repository structure for v0.11.4 is not compliant
```

**Comment by evildad** [comment]
Why do you want to add it via custom repo? It's officially available via hacs...

**Comment by kamahat** [comment]
I did not find it with names : "automoli", "AutoMoLi", "Ad-AutoMoLi", "ad automoli" in HACS so I've tried to add the repository entirely.

**Comment by evildad** [comment]
You should find it with those search strings... so just a question? Did you enable AppDaemon Apps on Hacs? https://hacs.xyz/docs/categories/appdaemon_apps/

**Comment by kamahat** [comment]
I did not know that was in a separate part of HACS.
