### ISSUE TITLE
Lights manually turnOff does not turnOn when motion

### ISSUE THREAD

**Issue by jompa68** [benleb/ad-automoli#17]
If i manually turnOFF a light, it does not turnON when movement if other lights already are ON. I must turn all OFF first.
Mistake in setup or bug?

**Comment by benleb** [comment]
If you mean other lights in the same room, thats intentionally behavior. The case for me was that if I manually change the light brightness or color or something in a room, I do not want that to be changed by automoli on movement.

**Comment by benleb** [comment]
Closing this for now, feel free to reply here again if you think we should discuss this further :)
