### ISSUE TITLE
[HELP] Where should i put config ?

### ISSUE THREAD

**Issue by gogui63** [benleb/ad-automoli#18]
I tried to put config like this in configuration.yaml but it seems to be not the right place ?
Where i should to write this ? Which folder / file ?

`
sdb_lights:
  module: automoli
  class: AutoMoLi
  room: sdb
  delay: 300
  daytimes:
    - { starttime: "05:30", name: morning, light: 45 }
    - { starttime: "07:30", name: day, light: "Travail" }
    - { starttime: "20:30", name: evening, light: 90 }
    - { starttime: "22:30", name: night, light: 0 }
  humidity_threshold: 75
  lights:
    - light.sdb
  motion:
    - binary_sensor.motion_sensor_sdb
  humidity:
    - sensor.humidity_sdb
`

Thanks , i am starting with home assistant

**Comment by benleb** [comment]
this is not a home assistant integration but an appdaemon app :) see here for how to use appdaemon https://appdaemon.readthedocs.io/en/stable/

if you encounter any problems regarding automoli itself, feel free to open another issue 👍
