### ISSUE TITLE
Bath mode

### ISSUE THREAD

**Issue by atterdal** [benleb/ad-automoli#20]
Hi,

Today i have a simple solution that overrides the "off" automation if i activate the "bath time" mode. Then the automation starts over next time it detects motion (by deactivating the bath time-mode)

Would something like this be possible to add?

**Comment by benleb** [comment]
Ah I call this the "shower case" :D This was implemented after my girlfriend had the first shower with AutoMoLi enabled :D
Do you have a humidity sensor (often integrated in temperature sensors) in your bathroom? You can then set a `humidity_threshold` in config - if this is reached/passed (like when you have shower), the lights will not switched off :) To find a suiteable value for your home, I suggest looking at your graphs. The spikes when someone is having a shower a very clear :)
![image](https://user-images.githubusercontent.com/512997/74103857-d9fda600-4b4f-11ea-82ab-9fdfd0dfed72.png)

**Comment by atterdal** [comment]
I do, it doesn't work well though. I have the aeotec multisensor 6.

Haven't understood if it doesn't work because it's "relative humidity" (heat and humidity rises at the same time). But I don't get any significant humidity rise until i open the door (cold air comes in). It could also be because it's a new house and the ventilation is to good (the mirrors barely fog up)

I have it recessed mounted in the ceiling, thought the was the reason first but tried another one and with the same result.

Hence, the bath time button 😊

Cheers,
Stefan

**Comment by benleb** [comment]
Okay, sounds reasonable... What do you think about an input_boolean, like the `disable_switch_entity`? That should do the job and should be easy to use from Home Assistants Lovelace or any other source.

**Comment by samnewman86** [comment]
I have a sensor on the pipe going to the shower, when this detected water flow it mark a shower in use Boolean to on, which could then be used to hold the lights on, fan on etc. Is this an option

**Comment by atterdal** [comment]
Input_boolean would be great for my use case as well. Then I could trigger it with two automations. One that turns Input_boolean of of "Bath Time" is activated and one that turns it back on when it detects motion again if Bath Time is activated.

**Comment by evildad** [comment]
The Input_boolean solution should be possible since a very long time now. Feel free to reopen if this is still an issue.
