### ISSUE TITLE
Allow sunset/sunrise + offset for daytimes

### ISSUE THREAD

**Issue by chbndrhnns** [benleb/ad-automoli#30]
If I would like my light to switch on only in darkness, it would be nice to have a setting that takes the current sunrise/sunset time plus an additional offset as input for daytime.

Deconz even [exposes](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/987#issuecomment-444191773) a `dark` attribute on their sensors which can be configured using the Deconz API. Maybe this would useful, as well.

**Comment by benleb** [comment]
I think using a binary_sensor which uses the sun.sun entity to show if its day/night would be the cleaner way to implement this. This sensor can then be used as `disable_switch_entity` for AutoMoLi.

If thats not a good Idea for some reasons, tell me and I (maybe ;)) will reopen 👍

**Comment by Klagio** [comment]
is a solution, but I think sunset and sunrise is more readable, cleaner

**Comment by Klagio** [comment]
> I think using a binary_sensor which uses the sun.sun entity to show if its day/night would be the cleaner way to implement this. This sensor can then be used as `disable_switch_entity` for AutoMoLi.
> 
> If thats not a good Idea for some reasons, tell me and I (maybe ;)) will reopen 👍

thats a solution, but then again if you need offset is additional programming needed. Wish to have a simple sunset + hh.ss  command
