### ISSUE TITLE
Lights turn off even when disable switch is turned off

### ISSUE THREAD

**Issue by mendevi** [benleb/ad-automoli#32]
Below is my app config. Even when I turn the disable switch on (off) my light still shuts off after the 60 second delay. I'm not sure if I'm doing something wrong or its a bug. My disable switch is an input boolean and it does halfway work. When deactivated the lights will not turn on by motion, but if I manually turn them on and motion is detected the count down still starts. 
I use SmartThings motion detectors, if knowing that makes a difference.
`################################################################################
### Kitchen Light Motion App ###
kitchen:
  module: automoli
  class: AutoMoLi
  room: kitchen
  disable_switch_entity: input_boolean.motion_kitchen
  delay: 60
  daytimes:
    - { starttime: "00:00", name: overnight, light: 10 }
    - { starttime: "05:30", name: early_morning, light: 25 }
    - { starttime: "07:00", name: morning, light: 45 }
    - { starttime: "08:55", name: day, light: 0 }
    - { starttime: "16:45", name: evening, light: 65 }
    - { starttime: "20:30", name: night, light: 50 }
    - { starttime: "22:00", name: more_night, light: 35 }
#  illuminance_threshold: 10
  lights:
    - light.kitchen_sink_light
  motion:
    - binary_sensor.kitchen_motion
  motion_state_on: "on"
  motion_state_off: "off"
`

**Comment by benleb** [comment]
Hey, perfectly observed :D At the moment it just disables switching on the lights, simply because that was sufficient for the initial use case. But I agree, it should completely disable AutoMoLi and it shouldn't be that hard to implement, added it to my todo :)

**Comment by mendevi** [comment]
@benleb thank you man, I wish I was up to par on Python and I could help out.
I'll let you know when I get there. Truly appreciate the app and time, this guy runs 90% of the lights in my house.

**Comment by mendevi** [comment]
@benleb with this closed is it good to go?
Just curious if any settings need to be updated on my end to test out.

**Comment by benleb** [comment]
Thanks ;) It should work without any changes on your side :) Give it a try -> [v0.6.1](https://github.com/benleb/ad-automoli/releases/tag/v0.6.1) 😁
