### ISSUE TITLE
how is scene suppoesd to work

### ISSUE THREAD

**Issue by thundergreen** [benleb/ad-automoli#35]
could you please add an ex ample and explain how scenes are supposed to work. I don't nderstand. I thought i can create scenes in hoeassistant and it will fire this scenes? can't find an example.

Thanks in advance :) I am porting all my automations to automili :) 

For me scenes are to set brightness color etc but i don't get this ruunning somehow :/

**Comment by efurban** [comment]
1. you can create your scene however you'd like to (e.g in HA)
2. use it like this: (the documentation has the scene name but missed "scene.". I found it out by try & error)
`  motion_state_on: "on"
  motion_state_off: "off"
  daytimes:
    - { starttime: "02:00", name: late_night, light: "scene.bathroom_lights_on_night" }
    - { starttime: "08:30", name: day, light: "scene.bathroom_lights_on_day" }
`

**Comment by thundergreen** [comment]
Thanks a lot! I found it out also by myself and thanks to the pull request which unfortunately has still not been merged 😝  https://github.com/benleb/ad-automoli/pull/31 Gesendet von Mail für Windows 10 Von: TravisGesendet: Donnerstag, 12. März 2020 15:29An: benleb/ad-automoliCc: ThUnD3r|Gr33n; AuthorBetreff: Re: [benleb/ad-automoli] how is scene suppoesd to work (#35) you can create your scene however you'd like to (e.g in HA)use it like this: (the documentation has the scene name but missed "scene.". I found it out by try & error)` motion_state_on: "on"motion_state_off: "off"daytimes: { starttime: "02:00", name: late_night, light: "scene.bathroom_lights_on_night" }{ starttime: "08:30", name: day, light: "scene.bathroom_lights_on_day" }`—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
