### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by mendevi** [benleb/ad-automoli#46]
Forgive me if this can be established with the current state of the application.

Situation.
I manually 'turn on' a light (say the hallway light)
The lights brightness is set to '100'
I then move and Automoli adjusts the brightness to '35' (which is what I have set up in the app)
But I want it to stay at '100' for this momentary use case.

I know I can disable the motion app with the input_boolean but I still want the light to turn off after 60 seconds of no motion.

Hopefully I made sense.

Thank you for the great app.

**Comment by benleb** [comment]
Hey, thanks! Do you mean automoli changes the brightness of a light that was manually turned on? Does this still occur with [v0.8.0](https://github.com/benleb/ad-automoli/releases/tag/v0.8.0)? :)

**Comment by mendevi** [comment]
As of this morning automoli changed the brightness of a light I manually turned on. I believe I was on v0.7.3.

I'm at work and just updated to 0.8.0.

When I get home I will check to see if it still occurs.

**Comment by mendevi** [comment]
Not sure if I made any configuration errors when I changed my apps.yml from the 'disable_switch_entity' to 'disable_switch_entities' and now the app is not working at all.
I'm not seeing anything in the log that might help me figure it out either.

So I'm not able to test the previously discussed situation.

Were there any other changes I need to update?

**Comment by mendevi** [comment]
Reverted back to 0.7.3 and my old confit (entity not entities) 
And all works perfect (except for the brightness changing on motion for manually switched lights)

**Comment by benleb** [comment]
should work now ;) sorry! tested with
```yaml
disable_switch_entities: [input_boolean.automoli]
```
and
```yaml
disable_switch_entities: input_boolean.automoli
```

**Comment by mendevi** [comment]
I appreciate the quick help man.
All is good on 0.8.1.

Thank you.
