### ISSUE TITLE
TypeError: 'async_generator' object is not iterable

### ISSUE THREAD

**Issue by ilarrain** [benleb/ad-automoli#48]
**When using v.0.8.0, v.0.8.1 and master, I get the following error:**

> 2020-08-06 14:42:02.055791 INFO AppDaemon: Loading App Module: /config/appdaemon/apps/ad-automoli/automoli.py
> 2020-08-06 14:42:02.105642 INFO AppDaemon: Initializing app sala using class AutoMoLi from module automoli
> 2020-08-06 14:42:02.228217 WARNING sala: ------------------------------------------------------------
> 2020-08-06 14:42:02.231024 WARNING sala: Unexpected error in worker for App sala:
> 2020-08-06 14:42:02.233421 WARNING sala: Worker Ags: {}
> 2020-08-06 14:42:02.236121 WARNING sala: ------------------------------------------------------------
> 2020-08-06 14:42:02.240342 WARNING sala: Traceback (most recent call last):
>   File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 143, in initialize_app
>     await init()
>   File "/config/appdaemon/apps/ad-automoli/automoli.py", line 176, in initialize
>     await self.build_daytimes(self.args.get("daytimes", DEFAULT_DAYTIMES))
>   File "/config/appdaemon/apps/ad-automoli/automoli.py", line 420, in build_daytimes
>     and any((await self.get_state(entity_id=entity, attribute="is_hue_group") for entity in self.lights))
> TypeError: 'async_generator' object is not iterable
> 2020-08-06 14:42:02.241793 WARNING sala: ------------------------------------------------------------

**v0.7.3 works fine.**

**My config:**

> sala:
>   module: automoli
>   class: AutoMoLi
>   room: Sala
>   disable_switch_entities:
>     - input_boolean.luz_sala_movimiento
>   delay: 180
>   daytimes:
>     - { starttime: "06:00", name: day, light: turn on }
>     - { starttime: "18:30", name: evening, light: turn on }
>   lights:
>     - light.sala
>   motion:
>     - binary_sensor.movimiento_sala
>     - binary_sensor.sensor_puerta_principal
>     - binary_sensor.puerta_principal
>   motion_state_on: "on"
>   motion_state_off: "off"

**Notes:**
Even though my lights are Hue, they are connected in Zigbee2Mqtt without a Hue bridge, and the group is configured as a LightGroup in Home Assistant.

Daytimes are configured this way because I don't want Automoli to handle brightness, as it is handled by Circadian Lighting custom component https://github.com/claytonjn/hass-circadian_lighting

**Comment by ilarrain** [comment]
Setting line 417 to false fixes the issue in master (in v0.8.1 raised aditional errors):
>             dt_is_hue_group = False

**Comment by benleb** [comment]
can you confirm that 707cc8f fixes this? :)

**Comment by benleb** [comment]
I also added a `disable_hue_groups` option, should finally resolve this. Thanks for reporting!
