### ISSUE TITLE
Lifx not lighting up sometimes

### ISSUE THREAD

**Issue by gardar** [benleb/ad-automoli#53]
I've got a few tradfri and lifx bulbs set up and while the tradfri bulbs work great the lifx bulbs are giving me some trouble.

Sometimes when automoli turns the lifx bulbs on they won't light up while the log shows no error and just shows the message that the bulb has been turned on.
The HomeAssistant interface also shows the bulb as turned on.
If I then manually turn the lifx bulb off and on in HomeAssistant it lights up just fine, with the brightness level that automoli had set.
Strangely this seems to happen more with the brightness set low, I already tried increasing the brightness by a few % but it didn't seem to help.

Any ideas what might be causing this or how I can debug this further?

**Comment by gardar** [comment]
Diagnosed this further, this seems to happen the first time the lights turn on after the brightness has changed. If I manually turn them off and then on again or if I wait for automoli to turn the lights off then next time they turn on they light up.
I didn't realize this at first as I have quite a long timeout set for that specific light, so while I was frustratingly trying to figure out why the light didn't work the light was never turned off by automoli.

**Comment by benleb** [comment]
Thanks! I will check this :)

**Comment by benleb** [comment]
Can you please check if this still occurs with current master? :)

**Comment by benleb** [comment]
if theres still an issue, we can reopen :)

**Comment by gardar** [comment]
Hi.
Sorry I didn't get a chance to test this earlier... I just did some testing today with the update and unfortunately it still behaves exactly the same as before!

**Comment by gardar** [comment]
Is there any info/logs I can provide to help you diagnose this further?

**Comment by benleb** [comment]
Yes!
Could you please set the `debug` option to `true` (possible for a single room) and then show the relevant part (+- 1-2min). This shows some additional output, the variables involved and their current values and such stuff... maybe you even can spot the problem yourself then 😁 

According to your research... If I understand the lifx way correctly, it could help to use two calls, the first to set the brightness/color and the second on to actually turn it on?
(or more strict: using two calls should just needed if brightness/color differs from the values from the last time the bulb was on, but that's just theory... two calls everytime wont hurt either...)

**Comment by benleb** [comment]
ok, closing for now but reopen is no problem ;)
