### ISSUE TITLE
Transition between daytimes

### ISSUE THREAD

**Issue by paviro** [benleb/ad-automoli#61]
🙄 **Is your feature request related to a problem? Please describe.**
When using different scenes per daytime they only change if the lights are turned off in between. If you for example have a scene at 8pm and one at 9pm the 9pm does not trigger when the light isn't turned off in-between.

😍 **Describe the solution you'd like**
Set the scenes / brightness based on daytime and not only based on switching the light on and then checking which scene to use. Also allow the use of scene / light transitions for lights that support it so scenes can be smoothly switched.

🖼️ **Example/See here!** 

**Additional context**

**Comment by oscfor** [comment]
I have observed the same phenomenon.

**Comment by benleb** [comment]
That's intentional :D But should be easy to also implement a direct transition which can be activated via an option... give me a moment...

**Comment by benleb** [comment]
ok, the name of the option isn't very sexy yet, but (in a quick test) it works :)

set `transition_on_daytime_switch` to `true`, implemented in the mentioned commit

**Comment by benleb** [comment]
ah, transitioning is still missing, but would be cool if you could confirm that the already implemented variant works for you 👍

**Comment by paviro** [comment]
I can confirm this works 👍🏼

**Comment by paviro** [comment]
Could it be that this enabled the new scene even if the lights aren’t on? When I woke up this morning all light where on and the times corresponded to the scene changes.

**Comment by benleb** [comment]
fuck good catch -.-^ will be fixed in next hours

**Comment by paviro** [comment]
No worries that’s what betas are for :D

**Comment by benleb** [comment]
released this as stable moments ago 😅 🤦‍♀️

**Comment by paviro** [comment]
Oh well never mind then haha :D

**Comment by benleb** [comment]
:D should work in https://github.com/benleb/ad-automoli/releases/tag/v0.9.1 :)

**Comment by paviro** [comment]
Perfect! Could we keep this open for now? For a potential future transition update :D

**Comment by benleb** [comment]
Please open a new one for an additional feature or another problem to keep things separate. Makes it easier to talk about and reference issues and also I have a better overview of what's really open (= work to do).

**Comment by paviro** [comment]
Sure thing 👍🏼
