### ISSUE TITLE
Feature Idea: when motion is cleared, but then motion is triggered again (before timer is up...), reset timer

### ISSUE THREAD

**Issue by jfrux** [benleb/ad-automoli#7]

**Comment by benleb** [comment]
Sorry, I think I do not understand this... you mean:

* motion triggered
* -> lights on
* motion cleared
* motion triggered
* - > cancel timer
* --> lights will stay on and not switched off by automoli

is this what you mean?! I am curious what the use case for this is? :D

**Comment by jfrux** [comment]
Okay so...
Set delay to like... something ridiculous like 10 seconds to test.
Turn a light on (manually with a switch).
Move around the room and don't stop moving...
Light still turns off at like 10 seconds in some cases.

Also, if the motion is cleared even for a second... like I stop moving for enough time for the motion sensor to clear... it will almost always turn off my lights even if motion is detected again before the 10 second timer.

Does that make more sense?

**Comment by benleb** [comment]
hm the timer gets reset in every motion event... are you using something other than xiaomi sensors? especially some sensors which just switch between on/off and do not send events at motion if they are already „on“?

**Comment by jfrux** [comment]
SmartThings Motion Sensors, EcoLink PIR, don’t know about Xiaomi?

**Comment by benleb** [comment]
okay, then it’s related to #12, i have also a fix implemented for it. @thundergreen is currently testing this fix and if it works for him also, I will do a new release today :)

**Comment by thundergreen** [comment]
@benleb just give me the commit and i will test :)

**Comment by benleb** [comment]
if you also like adventures @jfrux here is a version to test :) https://github.com/benleb/ad-automoli/issues/12#issuecomment-575304845

**Comment by benleb** [comment]
@jfrux can you confirm its fixed with [v0.5.0](https://github.com/benleb/ad-automoli/releases/tag/v0.5.0)?

and don't miss to confirm #8 ;)

**Comment by jfrux** [comment]
They're showing as `xiaomi_aqara.motion` is that expected?
Having trouble with this bath room, gonna move upstairs and test a different room.

**Comment by jfrux** [comment]
Not sure I fully understand what triggers the app to show up scheduler list?

**Comment by benleb** [comment]
> They're showing as `xiaomi_aqara.motion` is that expected?
> Having trouble with this bath room, gonna move upstairs and test a different room.
Where do they show as xiaomi!?

> Not sure I fully understand what triggers the app to show up scheduler list?
The logic now works as described in this comment: https://github.com/benleb/ad-automoli/issues/12#issuecomment-575266459

Scheduled callbacks list in the appdaemon admin-ui? the state-change to "off" triggers the scheduling of a callback to switch of the lights

**Comment by benleb** [comment]
Ok, closing this for now :) If you think thats wrong, comment and I will reopen the issue :)
