### ISSUE TITLE
Testing scenarios

### ISSUE THREAD

**Issue by chbndrhnns** [benleb/ad-automoli#9]
Would you be able to suggest an approach for unit-testing the configured scenarios? I am wondering how this could be achieved.

**Comment by benleb** [comment]
You mean except walking around? :D 

AppDaemon provides a [time travel](https://appdaemon.readthedocs.io/en/dev/APPGUIDE.html#time-travel) feature which could probably also used for testing, but I have not used it so far.

**Comment by jfrux** [comment]
@benleb LMAO... it's actually funny... sitting in a bathroom for absolutely no reason with a laptop... testing this now.  Saw this, laughed loudly.

**Comment by chbndrhnns** [comment]
Then it seems like this testing framework might be the way to go :)

**Comment by benleb** [comment]
So i think this can be closed now?! If not, comment and I will reopen :)
